/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./packages/*/src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: 'var(--theme-primary-500)',
          hover: 'var(--theme-primary-600)',
          light: 'var(--theme-primary-400)',
          dark: 'var(--theme-primary-700)',
          soft: 'var(--ai-primary-soft)',
          medium: 'var(--ai-primary-medium)',
          glow: 'var(--ai-primary-glow)',
          50: 'var(--theme-primary-50)',
          100: 'var(--theme-primary-100)',
          200: 'var(--theme-primary-200)',
          300: 'var(--theme-primary-300)',
          400: 'var(--theme-primary-400)',
          500: 'var(--theme-primary-500)',
          600: 'var(--theme-primary-600)',
          700: 'var(--theme-primary-700)',
          800: 'var(--theme-primary-800)',
          900: 'var(--theme-primary-900)',
          950: 'var(--theme-primary-950)',
        },
        cyan: {
          DEFAULT: 'var(--ai-cyan)',
          soft: 'var(--ai-cyan-soft)',
          glow: 'var(--ai-cyan-glow)',
        },
        purple: {
          DEFAULT: 'var(--ai-purple)',
          soft: 'var(--ai-purple-soft)',
          glow: 'var(--ai-purple-glow)',
        },
        success: {
          DEFAULT: 'var(--ai-success)',
          soft: 'var(--ai-success-soft)',
          glow: 'var(--ai-success-glow)',
        },
        warning: {
          DEFAULT: 'var(--ai-warning)',
          soft: 'var(--ai-warning-soft)',
        },
        error: {
          DEFAULT: 'var(--ai-error)',
          soft: 'var(--ai-error-soft)',
          glow: 'var(--ai-error-glow)',
        },
        bg: {
          primary: 'var(--bg-primary)',
          secondary: 'var(--bg-secondary)',
          tertiary: 'var(--bg-tertiary)',
          elevated: 'var(--bg-elevated)',
          overlay: 'var(--bg-overlay)',
          hover: 'var(--bg-hover)',
          active: 'var(--bg-active)',
          selected: 'var(--bg-selected)',
          disabled: 'var(--bg-disabled)',
        },
        text: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          tertiary: 'var(--text-tertiary)',
          muted: 'var(--text-muted)',
          placeholder: 'var(--text-placeholder)',
          inverse: 'var(--text-inverse)',
          disabled: 'var(--text-disabled)',
        },
        border: {
          DEFAULT: 'var(--border-color)',
          light: 'var(--border-light)',
          medium: 'var(--border-medium)',
          strong: 'var(--border-strong)',
          focus: 'var(--border-focus)',
          error: 'var(--border-error)',
          success: 'var(--border-success)',
        }
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      boxShadow: {
        'glow-primary': 'var(--glow-primary)',
        'glow-success': 'var(--glow-success)',
        'glow-error': 'var(--glow-error)',
        'glow-cyan': 'var(--glow-cyan)',
        'glow-purple': 'var(--glow-purple)',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
        'slide-up': 'slideUp 0.4s cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-in-right': 'slideInRight 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
        'scale-in': 'scaleIn 0.2s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'pulse-slow': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'shimmer': 'shimmer 1.5s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
