import { apiClient, IS_DEV, type Page, type Result } from "@sdkwork/openchat-pc-kernel";
import type { Video, VideoComment, VideoFilter, VideoStats, VideoType } from "../types";

const VIDEO_ENDPOINT = "/videos";
const favoriteVideosStorageKey = "openchat.video.favoriteVideos";
const recentVideosStorageKey = "openchat.video.recentVideos";
const maxRecentVideoCount = 20;
const now = Date.now();

const videoTypes: VideoType[] = ["neural", "matrix", "aurora", "cyber", "nature"];

const seedVideos: Video[] = [
  {
    id: "v1",
    title: "Neural Network Dreaming",
    description: "Watch AI visualize its own thoughts in real-time.",
    author: "Omni Vision",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Omni",
    thumbnail: "https://picsum.photos/400/600?random=101",
    url: "https://example.com/video1.mp4",
    duration: 45,
    likes: 102000,
    views: 580000,
    comments: 882,
    shares: 1200,
    type: "neural",
    hasLiked: false,
    hasCollected: false,
    tags: ["AI", "Neural", "Generative"],
    createTime: now - 8 * 60 * 60 * 1000,
    updateTime: now - 8 * 60 * 60 * 1000,
  },
  {
    id: "v2",
    title: "Data Stream Flow",
    description: "Visualizing big data in motion.",
    author: "Tech Core",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Tech",
    thumbnail: "https://picsum.photos/400/600?random=102",
    url: "https://example.com/video2.mp4",
    duration: 32,
    likes: 56000,
    views: 320000,
    comments: 341,
    shares: 560,
    type: "matrix",
    hasLiked: false,
    hasCollected: false,
    tags: ["Matrix", "Data", "Tech"],
    createTime: now - 10 * 60 * 60 * 1000,
    updateTime: now - 10 * 60 * 60 * 1000,
  },
  {
    id: "v3",
    title: "Aurora AI",
    description: "Northern lights generated by artificial intelligence.",
    author: "Nature Bot",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nature",
    thumbnail: "https://picsum.photos/400/600?random=103",
    url: "https://example.com/video3.mp4",
    duration: 58,
    likes: 218000,
    views: 1200000,
    comments: 1200,
    shares: 3400,
    type: "aurora",
    hasLiked: true,
    hasCollected: false,
    tags: ["Aurora", "Nature", "Beautiful"],
    createTime: now - 5 * 60 * 60 * 1000,
    updateTime: now - 5 * 60 * 60 * 1000,
  },
  {
    id: "v4",
    title: "Cyberpunk City",
    description: "A journey through futuristic cityscapes.",
    author: "Creative AI",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Creative",
    thumbnail: "https://picsum.photos/400/600?random=104",
    url: "https://example.com/video4.mp4",
    duration: 67,
    likes: 89000,
    views: 450000,
    comments: 556,
    shares: 890,
    type: "cyber",
    hasLiked: false,
    hasCollected: true,
    tags: ["Cyberpunk", "City", "Future"],
    createTime: now - 7 * 60 * 60 * 1000,
    updateTime: now - 7 * 60 * 60 * 1000,
  },
  {
    id: "v5",
    title: "Forest Meditation",
    description: "Relax with AI-generated forest scenes.",
    author: "Zen Master",
    authorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Zen",
    thumbnail: "https://picsum.photos/400/600?random=105",
    url: "https://example.com/video5.mp4",
    duration: 120,
    likes: 45000,
    views: 280000,
    comments: 234,
    shares: 450,
    type: "nature",
    hasLiked: false,
    hasCollected: false,
    tags: ["Nature", "Relax", "Meditation"],
    createTime: now - 12 * 60 * 60 * 1000,
    updateTime: now - 12 * 60 * 60 * 1000,
  },
];

const seedCommentsByVideoId: Record<string, VideoComment[]> = {
  v1: [
    {
      id: "c1",
      videoId: "v1",
      userId: "u1",
      userName: "Tech Enthusiast",
      userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Tech",
      content: "This is amazing. The generation quality is very smooth.",
      likes: 234,
      createTime: Date.now() - 3600000,
    },
  ],
};

type PartialPage<T> = Partial<Page<T>> & { list?: T[]; pageSize?: number };

function createId(prefix: string): string {
  return `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2, 8)}`;
}

function toNumber(value: unknown, fallback = 0): number {
  const numeric = Number(value);
  return Number.isFinite(numeric) ? numeric : fallback;
}

function normalizeVideoType(value: unknown): VideoType {
  return typeof value === "string" && videoTypes.includes(value as VideoType)
    ? (value as VideoType)
    : "neural";
}

function toResult<T>(response: unknown, defaultData: T): Result<T> {
  if (response && typeof response === "object" && "success" in response) {
    const result = response as Partial<Result<T>>;
    return {
      success: Boolean(result.success),
      data: (result.data as T | undefined) ?? defaultData,
      message: typeof result.message === "string" ? result.message : undefined,
      error: typeof result.error === "string" ? result.error : undefined,
      code: typeof result.code === "number" ? result.code : undefined,
    };
  }

  if (response && typeof response === "object" && "data" in response) {
    return { success: true, data: ((response as { data: T }).data ?? defaultData) as T };
  }

  if (response === undefined || response === null) {
    return { success: true, data: defaultData };
  }

  return { success: true, data: response as T };
}

function normalizeVideo(input: Partial<Video>): Video {
  const type = normalizeVideoType(input.type);
  const createTime = toNumber(input.createTime, Date.now());

  return {
    id: input.id || createId("video"),
    title: input.title || "Untitled Video",
    description: input.description,
    author: input.author || "Unknown",
    authorAvatar: input.authorAvatar,
    thumbnail: input.thumbnail || "https://picsum.photos/400/600?random=199",
    url: input.url || "https://example.com/video.mp4",
    duration: Math.max(1, toNumber(input.duration, 30)),
    likes: Math.max(0, toNumber(input.likes)),
    views: Math.max(0, toNumber(input.views)),
    comments: Math.max(0, toNumber(input.comments)),
    shares: Math.max(0, toNumber(input.shares)),
    type,
    hasLiked: Boolean(input.hasLiked),
    hasCollected: Boolean(input.hasCollected),
    tags: Array.isArray(input.tags) ? input.tags.filter((tag): tag is string => typeof tag === "string") : [],
    createTime,
    updateTime: toNumber(input.updateTime, createTime),
  };
}

function normalizeComment(input: Partial<VideoComment>): VideoComment {
  return {
    id: input.id || createId("comment"),
    videoId: input.videoId || "",
    userId: input.userId || "unknown",
    userName: input.userName || "Unknown",
    userAvatar: input.userAvatar,
    content: input.content || "",
    likes: Math.max(0, toNumber(input.likes)),
    createTime: toNumber(input.createTime, Date.now()),
  };
}

function normalizePage(input: unknown, page: number, size: number): Page<Video> {
  const payload = input as PartialPage<unknown>;
  const source = Array.isArray(payload.content) ? payload.content : Array.isArray(payload.list) ? payload.list : [];
  const content = source.map((item) => normalizeVideo(item as Partial<Video>));
  const total = toNumber(payload.total, content.length);
  const currentPage = toNumber(payload.page, page);
  const currentSize = toNumber(payload.size ?? payload.pageSize, size);

  return {
    content,
    total,
    page: currentPage,
    size: currentSize,
    totalPages: toNumber(payload.totalPages, Math.max(1, Math.ceil(total / Math.max(1, currentSize)))),
  };
}

class VideoServiceImpl {
  private fallbackVideos: Video[] = seedVideos.map((item) => ({ ...item }));
  private fallbackCommentsByVideoId: Record<string, VideoComment[]> = Object.entries(seedCommentsByVideoId).reduce(
    (acc, [videoId, comments]) => {
      acc[videoId] = comments.map((item) => ({ ...item }));
      return acc;
    },
    {} as Record<string, VideoComment[]>,
  );
  private favoriteVideoIds = new Set<string>();
  private recentVideoIds: string[] = [];

  constructor() {
    this.favoriteVideoIds = this.readFavoriteVideosFromStorage();
    this.recentVideoIds = this.readRecentVideosFromStorage();
  }

  private async withFallback<T>(
    apiTask: () => Promise<Result<T>>,
    fallbackTask: () => Result<T> | Promise<Result<T>>,
  ): Promise<Result<T>> {
    try {
      return await apiTask();
    } catch (error) {
      if (IS_DEV) {
        return fallbackTask();
      }
      throw error;
    }
  }

  private readFavoriteVideosFromStorage(): Set<string> {
    if (typeof localStorage === "undefined") {
      return new Set<string>();
    }

    try {
      const raw = localStorage.getItem(favoriteVideosStorageKey);
      if (!raw) {
        return new Set<string>();
      }
      const parsed = JSON.parse(raw) as unknown;
      if (!Array.isArray(parsed)) {
        return new Set<string>();
      }
      return new Set(parsed.filter((item): item is string => typeof item === "string"));
    } catch {
      return new Set<string>();
    }
  }

  private persistFavoriteVideos(): void {
    if (typeof localStorage === "undefined") {
      return;
    }
    localStorage.setItem(favoriteVideosStorageKey, JSON.stringify(Array.from(this.favoriteVideoIds)));
  }

  private readRecentVideosFromStorage(): string[] {
    if (typeof localStorage === "undefined") {
      return [];
    }

    try {
      const raw = localStorage.getItem(recentVideosStorageKey);
      if (!raw) {
        return [];
      }
      const parsed = JSON.parse(raw) as unknown;
      if (!Array.isArray(parsed)) {
        return [];
      }
      return parsed
        .filter((item): item is string => typeof item === "string")
        .slice(0, maxRecentVideoCount);
    } catch {
      return [];
    }
  }

  private persistRecentVideos(): void {
    if (typeof localStorage === "undefined") {
      return;
    }
    localStorage.setItem(
      recentVideosStorageKey,
      JSON.stringify(this.recentVideoIds.slice(0, maxRecentVideoCount)),
    );
  }

  getFavoriteVideoIds(): string[] {
    return Array.from(this.favoriteVideoIds);
  }

  isVideoFavorite(videoId: string): boolean {
    return this.favoriteVideoIds.has(videoId);
  }

  toggleFavoriteVideo(videoId: string): boolean {
    if (this.favoriteVideoIds.has(videoId)) {
      this.favoriteVideoIds.delete(videoId);
      this.persistFavoriteVideos();
      return false;
    }

    this.favoriteVideoIds.add(videoId);
    this.persistFavoriteVideos();
    return true;
  }

  getRecentVideoIds(): string[] {
    return [...this.recentVideoIds];
  }

  markVideoOpened(videoId: string): string[] {
    const filtered = this.recentVideoIds.filter((id) => id !== videoId);
    this.recentVideoIds = [videoId, ...filtered].slice(0, maxRecentVideoCount);
    this.persistRecentVideos();
    return [...this.recentVideoIds];
  }

  resetWorkspaceState(): void {
    this.favoriteVideoIds = new Set<string>();
    this.recentVideoIds = [];

    if (typeof localStorage !== "undefined") {
      localStorage.removeItem(favoriteVideosStorageKey);
      localStorage.removeItem(recentVideosStorageKey);
    }
  }

  private queryFallback(filter: VideoFilter): Video[] {
    return this.fallbackVideos
      .filter((item) => (filter.type ? item.type === filter.type : true))
      .filter((item) => {
        if (!filter.search?.trim()) {
          return true;
        }
        const lower = filter.search.toLowerCase();
        const target = `${item.title} ${item.description || ""} ${item.tags.join(" ")}`.toLowerCase();
        return target.includes(lower);
      })
      .sort((a, b) => b.likes + b.views * 0.1 - (a.likes + a.views * 0.1));
  }

  async getVideos(filter: VideoFilter = {}, page: number = 1, size: number = 12): Promise<Result<Page<Video>>> {
    return this.withFallback(
      async () => {
        const fallbackData = normalizePage({ content: [], total: 0, page, size }, page, size);
        const response = await apiClient.get<unknown>(VIDEO_ENDPOINT, {
          params: {
            type: filter.type,
            search: filter.search,
            page,
            size,
          },
        });
        const result = toResult<unknown>(response, fallbackData);
        if (!result.success) {
          return { ...result, data: fallbackData };
        }

        if (Array.isArray(result.data)) {
          const content = result.data.map((item) => normalizeVideo(item as Partial<Video>));
          return {
            ...result,
            data: {
              content,
              total: content.length,
              page,
              size,
              totalPages: Math.max(1, Math.ceil(content.length / size)),
            },
          };
        }

        return { ...result, data: normalizePage(result.data, page, size) };
      },
      () => {
        const filtered = this.queryFallback(filter);
        const start = (page - 1) * size;
        const content = filtered.slice(start, start + size).map((item) => ({ ...item }));
        return {
          success: true,
          data: {
            content,
            total: filtered.length,
            page,
            size,
            totalPages: Math.max(1, Math.ceil(filtered.length / size)),
          },
        };
      },
    );
  }

  async getVideoById(id: string): Promise<Result<Video | null>> {
    return this.withFallback(
      async () => {
        const response = await apiClient.get<unknown>(`${VIDEO_ENDPOINT}/${id}`);
        const result = toResult<unknown>(response, null);
        if (!result.success) {
          return { success: false, data: null, message: result.message || result.error };
        }
        if (!result.data) {
          return { success: true, data: null };
        }
        return { success: true, data: normalizeVideo(result.data as Partial<Video>) };
      },
      () => {
        const target = this.fallbackVideos.find((item) => item.id === id) || null;
        return { success: true, data: target ? { ...target } : null };
      },
    );
  }

  async toggleLike(id: string): Promise<Result<void>> {
    return this.withFallback(
      async () => {
        const response = await apiClient.post<unknown>(`${VIDEO_ENDPOINT}/${id}/like`);
        const result = toResult<unknown>(response, undefined);
        return result.success
          ? { success: true, message: result.message }
          : { success: false, message: result.message || result.error };
      },
      () => {
        this.fallbackVideos = this.fallbackVideos.map((item) => {
          if (item.id !== id) {
            return item;
          }
          const hasLiked = !item.hasLiked;
          return {
            ...item,
            hasLiked,
            likes: hasLiked ? item.likes + 1 : Math.max(0, item.likes - 1),
            updateTime: Date.now(),
          };
        });
        return { success: true };
      },
    );
  }

  async toggleCollect(id: string): Promise<Result<void>> {
    return this.withFallback(
      async () => {
        const response = await apiClient.post<unknown>(`${VIDEO_ENDPOINT}/${id}/collect`);
        const result = toResult<unknown>(response, undefined);
        return result.success
          ? { success: true, message: result.message }
          : { success: false, message: result.message || result.error };
      },
      () => {
        this.fallbackVideos = this.fallbackVideos.map((item) =>
          item.id === id ? { ...item, hasCollected: !item.hasCollected, updateTime: Date.now() } : item,
        );
        return { success: true };
      },
    );
  }

  async incrementViews(id: string): Promise<Result<void>> {
    return this.withFallback(
      async () => {
        const response = await apiClient.post<unknown>(`${VIDEO_ENDPOINT}/${id}/view`);
        const result = toResult<unknown>(response, undefined);
        return result.success
          ? { success: true, message: result.message }
          : { success: false, message: result.message || result.error };
      },
      () => {
        this.fallbackVideos = this.fallbackVideos.map((item) =>
          item.id === id ? { ...item, views: item.views + 1, updateTime: Date.now() } : item,
        );
        return { success: true };
      },
    );
  }

  async getComments(videoId: string): Promise<Result<VideoComment[]>> {
    return this.withFallback(
      async () => {
        const response = await apiClient.get<unknown>(`${VIDEO_ENDPOINT}/${videoId}/comments`);
        const result = toResult<unknown>(response, []);
        if (!result.success) {
          return { ...result, data: [] };
        }

        const list = Array.isArray(result.data)
          ? result.data.map((item) => normalizeComment(item as Partial<VideoComment>))
          : [];

        return { ...result, data: list };
      },
      () => {
        const list = this.fallbackCommentsByVideoId[videoId] || [];
        if (list.length > 0) {
          return { success: true, data: list.map((item) => ({ ...item })) };
        }

        const defaults: VideoComment[] = [
          {
            id: createId("comment"),
            videoId,
            userId: "u1",
            userName: "OpenChat User",
            userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=User",
            content: "Great visuals and pacing.",
            likes: 12,
            createTime: Date.now() - 3600000,
          },
          {
            id: createId("comment"),
            videoId,
            userId: "u2",
            userName: "AI Creator",
            userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Creator",
            content: "Would love to see behind-the-scenes prompts.",
            likes: 8,
            createTime: Date.now() - 7200000,
          },
        ];

        this.fallbackCommentsByVideoId[videoId] = defaults;
        return { success: true, data: defaults.map((item) => ({ ...item })) };
      },
    );
  }

  async getStats(): Promise<Result<VideoStats>> {
    return this.withFallback(
      async () => {
        const fallbackData: VideoStats = {
          totalVideos: 0,
          totalViews: 0,
          totalLikes: 0,
          byType: {
            neural: 0,
            matrix: 0,
            aurora: 0,
            cyber: 0,
            nature: 0,
          },
        };

        const response = await apiClient.get<unknown>(`${VIDEO_ENDPOINT}/stats`);
        const result = toResult<unknown>(response, fallbackData);
        if (!result.success) {
          return { ...result, data: fallbackData };
        }

        const payload = result.data as Partial<VideoStats>;

        return {
          ...result,
          data: {
            totalVideos: toNumber(payload.totalVideos),
            totalViews: toNumber(payload.totalViews),
            totalLikes: toNumber(payload.totalLikes),
            byType: {
              neural: toNumber(payload.byType?.neural),
              matrix: toNumber(payload.byType?.matrix),
              aurora: toNumber(payload.byType?.aurora),
              cyber: toNumber(payload.byType?.cyber),
              nature: toNumber(payload.byType?.nature),
            },
          },
        };
      },
      () => {
        const byType: Record<VideoType, number> = {
          neural: 0,
          matrix: 0,
          aurora: 0,
          cyber: 0,
          nature: 0,
        };

        this.fallbackVideos.forEach((item) => {
          byType[item.type] += 1;
        });

        return {
          success: true,
          data: {
            totalVideos: this.fallbackVideos.length,
            totalViews: this.fallbackVideos.reduce((sum, item) => sum + item.views, 0),
            totalLikes: this.fallbackVideos.reduce((sum, item) => sum + item.likes, 0),
            byType,
          },
        };
      },
    );
  }

  formatDuration(seconds: number): string {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, "0")}`;
  }

  formatCount(num: number): string {
    if (num >= 1_000_000) {
      return `${(num / 1_000_000).toFixed(1)}M`;
    }
    if (num >= 1_000) {
      return `${(num / 1_000).toFixed(1)}K`;
    }
    return `${num}`;
  }
}

export const VideoService = new VideoServiceImpl();
